spring:
  datasource:
    url: jdbc:postgresql://host.home.chyk.ink:15432/station
    username: station
    password: station_password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          smbx-world:
            client-id: "***REMOVED***"
            client-secret: "***REMOVED***"
            authorization-grant-type: authorization_code
            scope: "user.read"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          smbx-world:
            authorization-uri: https://smbx.world/oauth/authorize
            token-uri: https://smbx.world/oauth/token
            user-info-uri: https://smbx.world/api/user
            user-name-attribute: nickname

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs
    csrf:
      enabled: true
      cookie-name: "XSRF-TOKEN"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security.servlet: DEBUG
    org.springframework.boot.actuate.endpoint.web: DEBUG
