spring:
  application:
    name: WorldStation
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

springdoc:
    api-docs:
        enabled: false
    swagger-ui:
        enabled: false
